---
version: "2"
services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - UMASK_SET=022 #optional
    volumes:
      - /home/deckard/dockerconfig/sonarr:/config
      - /home/deckard/PLEX/tv:/tv
      - /home/deckard/PLEX/landingzone:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - RUN_OPTS=run options here #optional
    volumes:
      - /home/deckard/dockerconfig/jackett:/config
      - /home/deckard/PLEX/landingzone:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - UMASK_SET=022 #optional
    volumes:
      - /home/deckard/dockerconfig/radarr:/config
      - /home/deckard/PLEX/movies:/movies
      - /home/deckard/PLEX/landingzone:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
    volumes:
      - /home/deckard/dockerconfig/transmission:/config
      - /home/deckard/PLEX/landingzone:/downloads
      - /home/deckard/PLEX/landingzone:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
